팁/깃허브로 커밋하기.md
로컬과 연결을 하지 않고 깃허브 내에서 파일을 업로드 하여 커밋이 가능함!!
=> [2021.02.01]팁 추가

1.그리디알고리즘/뒤집기_ghoon99.py
그리디 알고리즘 
모두 1로 만들거나 모두 0 으로 만드는 방법 중  최소 횟수를 출력 하면 된다.
```py
answer = min(1로 만드는 횟수,0으로 만드는 횟수)
print(answer)
``` 
0 또는 1 로 만드는 횟수를 구하는 함수를 만들었다.
연속된 숫자를 한번에 뒤집으므로 연속되면 넘기고
연속이 끊기면 뒤집음 처리를 하여 카운트가 올라간다.
연속 체크 인덱싱 오류 때문에 0~길이-1 만 돌고
마지막 string[-1] ( 문자열의 맨뒤 문자) 를 따로 체크해줘야 한다.
=> [2021.01.16]ghoon99 뒤집기 풀이

1.그리디알고리즘/뒤집기_yangsooplus.py
단순하게 뒤집기만 해도 되는지, 혹은 몇번 꼬아서 뒤집으면 더 효율적으로 될 지 먼저 생각해봤습니다
예를 들어 000**1011**00 이라면, **1011**부분의 **0**을 **1**로 바꾼 후 **1111**을 **0000**으로 바꾸는 식으로요
결론은 저렇게 하나 그냥 다른 숫자가 나오자마자 바꾸나 **똑같습니다**
꼬아서 : 000101100 -> 000111100 -> 000000000
그냥   :  000101100 -> 000001100 -> 000000000
그래서 실제로 뒤집으며 계산할 필요없이 
연속된 0과 1의 세트 개수를 세서 작은 녀석을 찾기만 하면 되겠다 싶어 셌습니다. 
와중 min()은 또 까먹었습니다 지난 학기에도 맨날 까먹더니 여전하네요
=> [2021.01.16]yangsooplus 뒤집기 풀이

1.그리디알고리즘/kochanha_BOJ11399.py
리스트 정렬 후 for문에서 계속 더해가며 값을 얻음.
=> [2021.01.17]ATM_kochanha_BOJ11399.py

1.그리디알고리즘/ATM_yangsooplus.py
오름차순 정렬 후 cost_time 리스트에 소요 시간을 저장한 후 총합을 구했습니다
파이썬은 항상 리스트 초기 선언을 어떻게 할지 망설이게 되더라고요
다른분들은 어케 하시는지 참고하고 가겠습니다 😏
=> [2021.01.17] yangsooplus ATM 풀이

1.그리디알고리즘/ATM_ghoon99.py
어.. 문제에 설명대로 그대로 구현하니 정답이네요..
그래도 그리디 알고리즘이라 처음에 이렇게 접근을 해볼 생각이였는데..
문제를 더 자세히 보고 올려야겠어요 ㅜㅜ
여튼 리스트 컴프리헨션을 이용하여 값을 구했습니다..
=> [2021.01.17]ghoon99 ATM 풀이

1.그리디알고리즘/atm_suzyrhkr.py
처음에 아무 생각 없이 이중 for문으로 풀었는데.. 계속 이중 for문으로 먼저 풀게 된다 🥲
=> [2021.01.17] suzyrhkr ATM 풀이

2.구현/프린터큐_ghoon99.py
큐 구현을 위해 deque 모듈을 사용
리스트와 달리 왼쪽오른쪽에서 추가 삭제가 가능한 자료구조 입니당
```py 
deque.popleft()
deque.appendleft()
```
등등...
리스트 왼쪽이 앞쪽 , 오른쪽이 뒤쪽 이라고 하고
우선순위 비교를 위해 최대힙의 맨앞원소(최대값)과 비교를 하여 우선순위가 떨어지면
다시 줄의 맨 뒤로 돌려보냈다
그러다 우선순위가 젤 크면 인쇄와 동시에 큐에서 제거함
맨 앞의 원소를 삭제하면 그 다음으로 큰 원소가 맨앞으로 올라오는
최대 힙 을 사용하였다.
설명이 잘 안되네요 ㅠㅠ 왜 이렇게 풀었는지 물어보면 대답해드리겠슴니다..
지금 (01.18 5시쯤) 백준 채점서버 너무 느림 ㅠㅜㅠ~
=> [2021.01.18]ghoon99 프린터큐 풀이

2.구현/프린터큐_suzyrhkr.py
2018 자료구조 시험문제로 출제된 문제네요
pop과 del은 모두 지우고자하는 인덱스를 받아서 지우는 방식인데, 
pop()은 지워진 인덱스를 반환하지만 del은 값을 반환하지 않아서 단순히 값을 지우고자 하는 경우에는 del을 쓰는 게 수행속도가 조금 더 빠르다고 합니다 :)
=> [2021.01.18] suzyrhkr 프린터큐 풀이

2.구현/프린터 큐_yangsooplus.py
처음의 입력 순서를 중요도와 같이 보존하는게 키포인트였던 문제입니다.
이상한 고집으로 딕셔너리쌍을 리스트에 넣어서
최대값이 pop되어 나갈 때, key값을 판별하여 
우리가 원하는 값이 나올때를 판별하려고 1시간을 잡았다가
포기하고 배열 두개 쓰니까 금방 끝나네요 ㅎㅎ;
사실 저는 소융대내 게임 제작 동아리에 소속되어 있습니다
얼마전까지 C#으로 csv파일을 불러들여 게임에 적용하는 기능을 개발했는데요
딕셔너리의 value에 리스트 배열을, 리스트의 요소에 딕셔너리를 넣는 등
요리조리 활용해 구현했어서 파이썬에서도 할 수 있나? 하고 시도해봤습니다
결론은  C#와 비교했을 때 리스트 속의 딕셔너리의 key에 접근하는게 힘들더라고요
value값은 queue[i][i]와 같이 2차원 배열처럼 접근이 가능했습니다 
**queue[i]** 여기까지가 리스트 요소에 접근, queue[i]**[i]** 이걸로 딕셔너리 value 접근 
근데 이 시점에서 _"엑 그냥 리스트 두개 쓰면 되잖아"_ 하고 포기하고 리스트로 했습니다 
역시 심플 이즈 베스트
=> [2021.01.18] yangsooplus 프린터 큐 풀이

2.구현/톱니바퀴_ghoon99.py
빡센 구현이네요 ㅠㅠ..
처음에 문제를 **먼저 선택된 톱니를 회전시킨 후** 에 
돌아간 걸 기준으로 나머지를 돌리는 줄 알았는데
문제를 잘못 읽었네요.. **먼저 돌릴 톱니를 결정 후**에
마지막에 돌릴 톱니를 한번에 돌리는게 맞네요..
돌릴때 deque 자료구조를 이용하여 `deque.rotate()` 메소드를 이용해서 
쉽게 요소들을 앞으로 밀고 댕기고 할 수 있어유
collections.deque 는 문제 풀때 엄청 유용하니 한번 꼭 공부해보길 바랍니당..
=> [2021.01.19]ghoon99 톱니바퀴 풀이

3.그래프 이론_탐색/DFS와BFS_ghoon99_.py
알고리즘 시간에 c 로 구현했던 dfs bfs 를 파이썬으로 직접 구현하면 되네요
그래프는 인접리스트로 표현했고 입력값을 오름차순으로 정렬해야되네요
dfs는 재귀함수로
bfs 는 큐를 deque 를 이용해서 구현하였습니다
=> [2021.01.20]ghoon99 DFS와 BFS 풀이

3.그래프 이론_탐색/섬의 개수_ghoon99.py
그래프 탐색 bfs dfs 의 기본 틀이 되는 대표 문제라고 하네요..
그래프를 탐색하면서 연결된 모든 노드를 상하좌우 대각을 살펴보며 
재귀를 이용한 dfs로 문제를 풀었습니다..
처음에 재귀에러로 런타임 에러가 뜨길래 검색해봤더니 최대깊이를 초과하여 
맨위에  
```py
import sys
sys.setrecursionlimit(10**6)
````
를 쓰니  바로 통과가 되네요
=> [2021.01.21]ghoon99 섬의 개수 풀이

3.그래프 이론_탐색/boj1260_suzyrhkr_py.py
=> [2021.01.21] suzyrhkr BOJ1260 풀이

4.정렬/boj1181_suzyrhkr.py
입력받은 단어들을 리스트에 append 해준 뒤, 중복된 값을 출력하지 않기 위해 'set' 함수를 이용했다.
문제에선 우선순위가 길이이지만 사전순으로 정렬을 해주고나서 길이순으로 정렬을 해주는 방법으로 문제를 해결했다.
길이로 먼저 정렬을 하게 되면 사전순으로 정렬하는 것이 더 복잡해진다.
=> [2021.01.22] suzyrhkr BOJ1181 풀이

4.정렬/단어정렬_ghoon99.py
sort 함수의 키를 이용하여 정렬하는 방법
문자열이 있을때 기본 정렬은 알파벳 순서
key 를 길이로 지정하여 정렬
=> [2021.01.22]ghoon99 단어정렬 풀이

4.정렬/단어 정렬_yangsooplus.py
겨우 세이프
버블말고 다른 정렬 연습차
선택정렬 해봤습니다
파이썬의 요소 유무 판별은 정말 편하네요 
>     if input_word not in words:
=> [2021.01.22]yangsooplus 단어정렬 풀이

4.정렬/국영수_ghoon99.py
어제 처럼 먼저 뒤에 조건들부터 맞춰주고
위로 올라오면 되네요
근데 input이 반복문 안에 들어있어서 빠른 입력이 필요한가봐요
stdin.readline() 을 써야지 시간초과가 안나는듯 하네요 ㅠㅠ
=> [2021.01.23]ghoon99 국영수 풀이

5.이진탐색/ghoon99_숫자카드.py
이진탐색 연습겸 직접 탐색코드를 짜서 실행..
if a in b 에서 
in 연산자의 시간복잡도에 대해 알아보았는데
list,tuple에서는 O(n) 이고
set이나 dict 에서는 O(1) worst 에서 O(n) 이라네요
해시를 이용하여 자료를 저장해서 찾는게 빠른듯..
=> [2021.01.24]ghoon99 숫자카드 풀이

5.이진탐색/숫자 카드_yangsooplus.py
쓰읍 또 그놈의 시간초과
슬라이싱 이용해서 했는데 이게 문제인거 같네요 아마도?
> 
7 | Slice | l[a:b] | O(b-a) | 슬라이싱되는 요소들 수 만큼 비례
-- | -- | -- | -- | --
바쁜일 처리하고 나서 그냥 얌전히 인덱스로 해볼랍니다
=> [2021.01.24] yangsooplus 숫자 카드 풀이

5.이진탐색/ghoon99_랜선 자르기.py
아...
이진 탐색을 이용하여  조건을 확인하여 up down 게임을 하는거네요..
58퍼에서 계속 틀리길래 왜 그랬나 그냥 잡다한거 다 뺸 이진탐색만 하니까 통과됨 .....
**파라메트릭 서치** 를 공부해야겠다
=> [2021.01.25]ghoon99 랜선 자르기 풀이

6.다이나믹 프로그래밍/ghoon99_1로 만들기.py
점화식 세우는게 어렵다..
상향식 bottom-up 방식으로 해결 
트리 구조를 그려보고 생각해보자
=> [2021.01.26]ghoon99 1로만들기 풀이

6.다이나믹 프로그래밍/2n타일링_yangsooplus.py
저번에 유사한 문제를 풀었어서 금방 풀 수 있었네요
그림 첨부가 되지 않아 첨부는 못하지만 
그림판으로 하나씩 그려가다 보니 
지난 풀이가 생각이 나더라구요
=> [2021.01.27] yangsooplus 2n타일링 풀이

6.다이나믹 프로그래밍/ghoon99_2xn 타일링.py
무식하게 5번째 까지 그림 그리다가 
우연히 점화식을 발견했네요..
dp 다른문제 많이 풀어봐야겠어요 점화식 세우는게 우연으로 발견하는거 밖에 못하겠네 ㅠㅠ
=> [2021.01.27]ghoon99 2xn 타일링 풀이

7.최단경로/ghoon99_경로 찾기.py
마찬가지로 알고리즘 수업 마지막 부분인 플루이드 워셜 경로 알고리즘을 변형하였습니다.
삼중포문으로 구현하기는 쉬운데 개념 이해가 살짝 힘들었어요 ㅜㅜ
0 or 1 만 있어서 true false 로 생각을 해서 경로가 있을때 1 로 하게 변형하였습니다..
=> [2021.01.29]ghoon99 경로 찾기 풀이

1.그리디알고리즘/회의실 배정_ghoon99.py
풀었는데 푼거같지가않네요 어려워...
n^2(모든 경우의 수를 구함)은 절대 안될거같아 다른 방식을 고민해봤는데
시간을 점프 점프 하면서 이미 갔던곳은 안가게 하는 방식으로 하려니 넘 어렵고
메모리도 많이먹고.. 결국 최악의경우 n^2인건 똑같더라구요
그래서 그리디 알고리즘이라는걸 다시 생각해보고 
순간순간의 제일 최선의 방법이 있을거라 생각을 해봤는데
정렬기준을 막 요리조리 바꿔보니까 되긴하더라구요
처음엔 start 를 기준으로 정렬하고
end - start 를 기준으로 또 오름차순을 하였는데 틀렸다 나오고
end기준 ->start 기준 도 해보고
start 기준->end 기준도 해보고
딱 1번 순차탐색 반복문 1번만 돌려보면서 카운트를 구했는데
통과가 되네욛ㄷ 
비슷한 문제를 코테에서 푼거같은 기분이 드네요..
갈길이 멀지만 하루하루 앞으로..
=> [2021.01.30]ghoon99 회의실 배정 풀이

1.그리디알고리즘/주식_ghoon99.py
최대 이익을 위해 
**낮을때 사고 떨어질때 팔고** 를 해봤는데 그게 최대 이익이 아니더라구요...
그다음 제일 높은 가격까지 사기만 하다가 제일 높을때 팔았는데.. 그거도 안되고
결국 
지금부터 팔시기가 이미 정해진거였습니다(앞으로 제일 최대값)
근데 최대값을 계속 찾자니 n^2 이 되어버리고
해답중에 뒤에서부터 훑으면 한번에 탐색이 가능해지더라구요
이미 가격을 다 알고있어서 가능한가 봅니다..
그리디 알고리즘
**매번 선택이 항상 최고의 이익을 가져오나 검증을 해볼 것**
=> [2021.01.31]ghoon99 주식 풀이

2.구현/괄호의 값_ghoon99.py
스택을 이용하여 괄호가 맞는지 확인 하는 코드는 되는데
점수를 어떻게 넣으라는건지 도저히 구현이 안되네요 ㅜㅜㅜㅜㅜㅜ
하..
=> [2021.02.02]ghoon99 괄호의 값 풀이 

1.그리디알고리즘/주유소_gusdn3477.py
제가 푼 방식으로 핵심 아이디어를 설명하겠습니다.
주유소를 지나가며 리터 당 가격이 가장 저렴한 주유소 가격을 저장하고, (0번 인덱스의 주유소 리터당 가격으로 초기화 합니다.)
현재 주유소 리터 당 가격과 비교하며,
1) 현재 주유소 리터 당 가격이 비싸면 -> 리터 당 가격이 가장 저렴한 주유소 가격 * 다음 주유소까지의 거리를 total에 더합니다.
2) 현재 주유소 리터 당 가격이 더 싸면 -> 리터 당 가격이 가장 저렴한 주유소 가격이 담긴 변수를 업데이트 후, 업데이트 된 변수 * 다음 주유소까지의 거리를 total에 더합니다.
즉, 이번에 이용하는 주유소가 싼지 비싼지 모르겠네? -> 일단 가격을 저장해 놓고 다음 주유소까지 갈 양만 충전하자
-> 저번 주유소가 더 싸네? -> 전에 저장해뒀던 값을 이용하자(이미 지나쳤지만 가격은 알고 있기에 이용 가능)
-> 저번 주유소가 더 비싸네? -> 싼 주유소 가격을 이번 주유소 가격으로 업데이트 한 뒤 다음 주유소 거리까지 충전해서 가자.
라고 생각하시면 됩니다.
초반에 몇 회의 실패를 거듭하였습니다. 이유로는 실시간으로 리터 당 가격이 저렴한 주유소 가격을 업데이트 하는 것이 아닌, 
min 함수로 리터 당 가격이 저렴한 주유소의 가격을 미리 구하고 시작하였기 때문입니다.
즉, 상대적으로 싼 주유소라도 최솟값이 아니면 단지 다음 주유소까지의 주유만 하게 되어 오차가 발생하게 되었습니다.
=> [2021.02.04]gusdn3477 주유소 풀이

1.그리디알고리즘/주유소_ghoon99.py
처음에 제일 싼곳까지 거리만 맞춰서 간다음 
제일 싼곳에서 끝까지 갈 기름을 다 넣는 방식으로 하였으나 틀렸습니다..
생각해보니 제일 싼 곳까지 가는 방식도 최소 비용이 들어야된다는 것을 알았습니다
```py
.....
price.pop()
min_price = min(price)
result = 0
pos = 0
for _ in range(n):
print(pos,result)
if price[pos] == min_price:
result += sum(dist[pos:])*min_price
break
result += dist[pos]*price[pos]
pos += 1
print(result)
```
그래서 몇가지 반례를 생각해보면서 
제일 싼 곳 까지 가면서 제일 적게 비용이 들게 해보니 이게 재귀적?으로 반복되더라구요
결국 그냥 자기보다 작은 값이 나올때까지 자기값으로 주유를 넣고 
작은 값이 나오면 값을 갱신해나가면 풀리네요..
또 `min*(dist1+dist2+dist3)` 식으로 최소가격인 곳에서 뒤에있는 거리를 누적하여 result 에 합하려했는데
그냥 반복문을 돌면서 `min*dist1+min*dist2...` 식으로 하면 되는군요..
=> [2021.02.04]ghoon99 주유소 풀이

1.그리디알고리즘/주유소_lys7442.py
매 순간 비용이 최소가 되어야 한다 라는 관점에 치중하여 문제를 풀었습니다.
따라서 매번 최솟값이란 것을 확신할 필요가 있었습니다.
이중 반복문으로 이전 비용들과 현재비용을 모두 비교하는 것이 가장 정확하지만 비효율적이기 때문에
최소비용을 변수에 저장하여 풀었습니다.
=> [2021.02.04] lys7442 주유소 풀이

그리디알고리즘/주유소_soyoonjeong.py
늦게 올려서 죄송해요ㅜㅠ풀리퀘 이렇게 하는거 맞나요?
들르는 도시마다 그 뒤에 있는 도시들과 가격을 비교해서 최소가격으로 기름을 사려고 했습니다!
=> [2021.02.05] soyoonjeong_주유소

1.그리디알고리즘/동전0_gusdn3477.py
핵심 아이디어는 '반대로 생각하기' 입니다. 즉, 여러 개의 동전들의 합을 조합하여 K원을 맞추지 말고,
K원에서 가치가 큰 동전들로 나누기/나머지 연산 등을 통하여 0원을 만들어 나가는 게 핵심인 것 같습니다.
입력받은 동전의 가치들을 내림차순 정렬을 통하여 가치가 큰 값이 리스트의 앞 요소에 오게끔 합니다.
반복문을 통하여 리스트의 각 요소들을 돌며, 동전의 갯수를 저장하는 변수에
현재 가지고 있는 돈 / 리스트의 현재 요소의 가치를 더하게끔 하였습니다.
또한, 다음 줄의 코드에서 현재 가지고 있는 돈을 현재 리스트의 요소와 나머지 연산을 통한 값으로 업데이트 하였습니다. 
만약, 현재 가지고 있는 돈보다 리스트 요소가 더 크게 되어도, 결과에 아무런 영향을 끼치지 않습니다.
자신보다 더 큰 값으로 나누면 0이고, 자신보다 더 큰 값으로 나머지 연산을 하면 자기 자신이기 때문입니다.
소요 시간을 줄이기 위하여 현재 가지고 있는 돈이 0이 되면 break를 통하여 반복문을 빠져 나오게 하였고,
출력문으로 답을 출력하는 식으로 문제를 풀었습니다.
운이 좋아서 잘 풀린 것 같습니다. 좋은 문제 감사합니다!
=> [2021.02.05] gusdn3477 동전0 풀이

1.그리디알고리즘/동전_jerimo.cpp
- 리스트를 사용하여 동전의 종류를 내림차순으로 관리하고, 동전 개수를 최소하 하기 위해 반복문을 사용하여 금액이 큰 동전부터 k/(동전의 금액)을 필요한 동전 개수에 더한 뒤 남은 금액은 나머지 연산자를 사용하여 계산해 주었다.
- c++의 list는 vector와 다르게 배열 원소에 자유롭게 접근할 수 없으므로 개수를 세고 난 뒤에는 리스트에서 pop해주어 다음 동전으로 넘어간다.
- push_front()는 앞에다 원소 삽입
- front()는 맨 앞의 원소 반환
- pop_front()는 맨 앞의 원소 삭제
오른쪽에 라벨이 뜨지 않음..  풀리퀘가 처음이라 미숙합니다! 코드는 성공한 코드입니다
=> [2021.02.05]jerimo 동전0 문제풀이

1.그리디알고리즘/동전 0_ghoon99.py
책에서 본 그리디 알고리즘에서 제일 기본이 되는 문제인 거스름돈 문제에서 생각을 해냈습니다
큰 단위부터 거꾸로 가지고 있는 돈을 덜어내는 식으로 작은단위까지 반복 하면 되는군요 
운이 좋아서 바로 풀었네요..
=> [2021.02.05]ghoon99 동전 0 풀이

1.그리디알고리즘/[2021.02.05] dydwo706 동전
중간 A.reverse() 이 부분을 처음에 안하고 밑에서 for a in reversed(range(N,0)) 이런 식으로 for문 범위에 변화를 주려고 했는데 
내림차순으로 계산이 안되고 오름차순으로만 나오네요,, 왜 그런지는 잘 모르겠어요ㅜ
=> [2021.02.05] dydwo706 동전0 풀이

1.그리디알고리즘/동전 0_soyoonjeong.py
입력받은 동전의 가치들을 내림차순으로 돌아보면서 k보다 작은 값이 나오면 필요한 동전 개수에 k에서 그 동전 가치를 나눈 몫을 더하는 식으로 구하였습니다. 
이렇게 더할 때마다 k도 갱신해주었고 k가 0이 되면 그 즉시 반복문을 탈출하도록 하였습니다.
=> [2021.02.05] soyoonjeong 동전 0 풀이

1.그리디알고리즘/동전0_yangsooplus.py
먼가.. 먼가.. 더 쇼킹한 풀이를 하고 싶었는데
깝치지 말고 기본대로 했읍니다
=> [2021.02.05] yangsooplus 동전0 풀이

1.그리디알고리즘/동전 0_lys7442.py
```
import sys
n,k = map(int,sys.stdin.readline().split())
a = [int(sys.stdin.readline()) for i in range(n)]
a.sort(reverse=True)
cnt=0
for i in a:
while(i<=k):
k-=i
cnt+=1
if(k==0):
break
print(cnt)
```
=> [2021.02.05] lys7442 동전0 풀이

2.구현/단어 뒤집기2_gusdn3477.py
문제 특성상 양 방향에서 뽑아내는 경우가 생기기에, collections의 모듈에 있는 deque을 import 하여 풀었습니다.
입출력 예시가 꽤 많이 주어져서 제출 전에 미리 테스트 해 볼 기회가 많은 친절한 문제였습니다.
핵심 아이디어는 입력받은 문자열 S를 돌며, 해당 인덱스의 값이 태그인지 아닌지만 구분하면 되는 것 같습니다.
그러기 위해서 flag라는 변수를 만들어 태그 모드인지, 아닌지 구분하게 하였습니다.
참고로 태그 모드란, '<' 를 만났고, '>'를 만나기 전 상태를 말합니다.
1) 태그 모드가 아니라면,(flag = 0) 
- 공백을 만난 경우 스택처럼 뒤에서 하나씩 출력해주면 됩니다.
- 그 외의 문자는 append 처리 해줍니다.
2) 태그인 경우,
- 여는 태그인 경우 flag 변수를 1로 설정한 뒤 deque에 담긴 문자열을 스택처럼 하나씩 뽑아 출력하면 됩니다. 
(여는 태그 이전의 모든 문자를 역순으로 출력한다고 보시면 됩니다.)
- 닫는 태그인 경우, flag 변수를 0으로 만들고 deque에 담긴 문자열을 큐처럼 하나씩 뽑아 출력하면 됩니다,
- 태그와 태그 사이 문자는 그냥 deque에 append 합니다.
3) 공백, 태그로 문자열이 종료되지 않는 경우를 위하여
코드 마지막 부분에 deque이 빈 상태가 아닐 때 까지 스택처럼 뒤에서 뽑아서 출력합니다.
공백, 태그로 문자열이 종료된 경우엔 deque가 비었기 때문에 코드가 실행되지 않을 것입니다.
=> [2021.02.06]gusdn3477 단어 뒤집기2 풀이

2.구현/단어뒤집기2_jerimo.cpp
처음에는 예외 보일때마다 마구잡이로 고쳐가며 코딩했더니
코드가 너무 지저분해지고 오히려 문제가 안풀리길래
싹 지우고 다시 생각했다. 
- 스택을 사용하면 빠르게 풀릴것 같아서
push pop 하는 식으로 문자열을 뒤집었고,
- 태그인지 확인하기 위해서 flag 변수를 두었다. flag가 false일 경우에만 문자열을 뒤집어서 출력한다.
- 공백을 포함한 문자열을 받기 위해 ```getline()```
- string 구조를 사용하면 ```pop```과 ```push```바로 사용 가능
ㅜㅠ 초대 수락햇는데 아직 라벨이 안떠서 못달았다.. 
성공한 코드입니다..!
=> [2021.02.06] jerimo 단어 뒤집기2 문제풀이

2.구현/단어 뒤집기 2_lys7442.py
처음 생각한 코드
```python
from collections import deque
S=input()
dq=deque()
for i in S:
if(i=='<' or i== ' ' ):
while(len(dq)>0):
print(dq.pop(),end="")
print(i,end="")
elif(i=='>'):
while(len(dq)>0):
print(dq.popleft(),end="")
print(i,end="")
else:
dq.append(i)
while(len(dq)>0):
print(dq.pop(),end="")
```
S는 태그와 단어로 구성된 문자열입니다.
Deque를 활용하여 태그 내의 값은 태그와 함께 순서대로 출력하고,
단어들은 역순으로 출력하는 코드를 작성했습니다. 
입력: `<ab cd>ef gh<ij kl>`
출력: `<ba cd>fe hg<ji kl>`
그러나 위와 같이 태그 안에 띄어쓰기가 발생한다면 역순으로 출력되기 때문에,
현재 상태가 태그 내에 있는지 아닌지를 구별할 필요가 생깁니다.
```python
from collections import deque
S=input()
tag=0
dq=deque()
for i in S:
if(i=='<'):
while(len(dq)>0):
print(dq.pop(),end="")
print(i,end="")
tag=1
elif(i=='>'):
while(len(dq)>0):
print(dq.popleft(),end="")
print(i,end="")
tag=0
elif(i==' 'and tag==0): …
```
=> [2021.02.06] 단어 뒤집기 2 풀이

2.구현/단어 뒤집기2_ghoon99.py
일단 의식의 흐름 대로 문제를 보자마자 구현을 했습니다
문자열을 쭉 돌면서
- < 일때
- \> 일때
-  공백일때 
- 그냥 일반 문자일때 로 나누었습니다
문자를 돌면서 임시 리스트에 문자 하나하나를 넣어
`['a','b','c']` 형태로 만들었고 
태그가 열림 닫힘을 open 변수를 두어 True False 일때 마다 행동을 다르게 만들었습니다
그래서 태그일때는 임시리스트를 ` "".join(list)` 를 이용하여 `['a','b','c']` 를 `"abc"`로 만들었고 
태그가 아닐때는 임시리스트를 한번 뒤집고 문자열로 만들었습니다.
결과적으로  result 에는 `['<tag>','54321','<close tag>']` 인 형태로
**공백 또는 태그를 기준으로 
분리되어 문자열로 저장** 되어있습니다
이것을 출력형식에 맞게 (공백 주의해서) 출력해주면 됩니다
그냥 있는대로 막 구현하다 보니 시간,공간 코드,효율이고 뭐고 없네요 ㅠㅠ
그래도 시간초과 안나고 통과는 했습니다..
=> [2021.02.06]ghoon99 단어 뒤집기2 풀이

2.구현/트럭_gusdn3477.py
(Review change 누르셔서 accept 해주시면 될 듯 합니다.)
개인적인 느낌으로, 지금까지 올라온 문제 중에 가장 어려웠습니다.
문제에서 주어진 내용을 바탕으로 잘 구현하면 풀리지만, 그 과정이 쉽지가 않았습니다.
저는 다리 위의 차량의 정보를 저장할 bridge와 다리에 진입하기 원하는 queue라는 이름의 두 개의 deque을 이용하여 문제를 해결하였습니다. 
핵심 아이디어는 '다리 위에 있는 시간을 기록해 두자.'와 '먼저 빠져나온 뒤, 새로 들어가라' 인 것 같습니다.
while 문으로 무한 루프를 돌게 하였고, 종료 조건으로 queue와 bridge가 모두 비었으면 종료하도록 하였습니다.
먼저, 매 시간마다 다리 위에 있는 차량들의 시간 변수들을 증가시켜 주었습니다. (리스트의 두 번째 요소가 시간입니다.)
1초마다 왼쪽으로 1씩 움직이므로, 다리 위에 있는 시간이 다리 길이보다 길어지면, 다리를 건넜다는 것을 의미하므로, 바로 bridge의 첫번째 요소를 pop 해줍니다. (먼저 pop을 해 줘야, 새로 진입할 차량이 들어올 수 있습니다.)
total_weight라는 변수를 0으로 초기화 하였고, 다리 위의 차량의 무게를 모두 더하였습니다.
다리 위의 차량이 모두 비어있으면(not bridge), 0으로 초기화하였고, 그렇지 않다면 각 리스트의 첫째 요소를 더했습니다.
(첫째 요소가 무게, 두번째 요소가 다리 위에 있는 시간을 의미합니다.
만약, 다리에 진입하기 원하는 차량이 queue에 존재한다면, (if queue)
queue의 첫째 요소(queue[0])과 …
=> [2021.02.07]gusdn3477 트럭 풀이

2.구현/트럭_ghoon99.py
문제에서 준 그림과 다르게 
왼쪽 -> 다리 -> 오른쪽 으로 보고 생각을 했습니다
양쪽에서 넣고 빼야되서 deque 를 사용하였습니다 
왼쪽엔 입력받은 배열을 큐로 사용할수있게 deque 로 만들었고
다리는 다리 길이만큼 [0,0,0,0] 0으로 초기화된 deque를 만들었습니다
오른쪽엔 이동이 완료된 트럭을 저장하여 이동완료된 트럭이 n 개가 되면 반복문을 종료하도록 하였습니다
다리에 있는 deque 의 합이 리밋이 넘어가지 않으면 올리고 아니면 0을 추가 하는 식으로 해서
다리에 **0 혹은 트럭** 을 추가하여 옆으로 밀었습니다 
약간 작년에서 파이썬으로 convolution 연산을 구현하는 과제를 했었는데 
0을 맨앞에 넣고 맨뒤 원소를 pop 해주는 리스트의 원소를 옆으로 미는 과정이 생각났나보네요
그냥 트럭이 다리를 건너가고 최대 무게를 넘어서면 못넘어가게 
말그대로 구현한거라 설명이 잘 안되네요 ㅠㅠ 
혹시 질문 드리면 답해드리겠슴다..
(다리) (도착)
=> [2021.02.07]ghoon99 트럭 풀이

3.그래프 이론_탐색/바이러스_jerimo.cpp
- 벡터(list)를 연결리스트처럼 사용해 그래프 표현
-  처음엔 단방향인줄 알고 ```from -> to```만 push 했는데 나중에 보니까 양방향이어서 양쪽 다 push 해줌
- 중복되는 컴퓨터는 세지 않기 위해 cnt 리스트를 사용해 리스트에 존재하지 않을 경우에만 삽입 후 리스트의 크기를 셈
- 탐색은 재귀적으로 함 (알고리즘 배운지 가물가물해서 내가 짠게 dfs인지 bfs인지 모르겠음..)
- 포인터? 참조연산자 너무 오랜만이라 처음 재귀 함수 짤때 cnt배열에 * 안붙여서 계속 값이 제대로 출력 안됐었음,, 
- ```vector```를 제외하고 c언어와의 큰 차이점은 없음
라벨문제는.. 제가 내일중으로 한번 해결해보겠습니다.. 하핳
=> [2021.02.08] jerimo 바이러스 문제풀이

3.그래프 이론_탐색/바이러스_ghoon99.py
DFS BFS 연습삼아 두개다 작성해보았습니다
인접 리스트를 이용하여 그래프를 표현하였습니다
알고리즘 시간에 배운 내용을 복습하는 느낌이 들었네요
=> [2021.02.08]ghoon99 바이러스 풀이

3.그래프 이론_탐색/단지번호붙이기_ghoon99.py
dfs 를 이용하였습니다
전체 맵을 훑어주면서 1이 있는 부분부터 dfs 를 실행하고
가는곳마다 다시 방문하지 않도록 0 으로 바꿔줍니다
전역변수 cnt를 사용하여 한번의 탐색때 몇개의 집이있나(1에서 0 으로 바꾼 개수)를 저장하고
house 배열에 저장하여 나중에 단지의 개수를 구할때 `len(house)`를 이용하였습니다
=> [2021.02.09]ghoon99 단지번호붙이기 풀이

3.그래프 이론_탐색/단지번호붙이기_jerimo.cpp
- 일단 공백이 없는 int를 입력받을 때 cin으로는 아직 방법을 못 찾았고
```scanf("%1d", &ar[i][j])```를 이용한다.
- i, j가 배열의 크기를 넘어간 경우 바로 종료한다.
- DFS를 이용해서 1을 찾으면 현재 위치의 상하좌우를 모두 탐색하고 방문한 배열은 v[i][j]를 1로 바꿔 다시 탐색하지 않도록 한다.
- ```main```에서 이중 for문을 이용해 탐색을 할 때, 이미 방문한 경우여서 cnt가 0인 채로 종료되는 경우가 있는데, 이럴 경우 li에 push 하면 안되므로 _cnt가 0이 아닐 때만_ push 하도록 한다.
=> [2021.02.09]/ jerimo 단지번호붙이기

4.정렬/시리얼 번호_ghoon99.py
조건에 따라 정렬을 3번하였습니다
먼저 사전순으로 정렬을 한뒤
자리수합 순으로 정렬을 하고
마지막으로 길이순 정렬을 하면 주어진 조건을 만족합니다
조건이 여러개가 있는 정렬을 할때 맨 나중에 있는 조건부터 맞춰줘서 거꾸로 올라가면 되는군요
자리수합을 구할땐 문자열에서 숫자를 뽑기위해 정규표현식을 이용하였습니다
=> [2021.02.10]ghoon99 시리얼 번호 풀이

4.정렬/시리얼 번호_ jerimo.cpp
- 얼마 전 정렬 문제를 풀다 새롭게 알게된
```C++의 algroithm 헤더에 들어있는 sort 함수```를 이용해서 간단하게 풀 수 있었다.
- 인자는 (배열의 시작점, 끝점, (필요시) 비교함수) 인데, 이 비교함수 compare를 상황에 맞게 짜면 정렬을 쉽게 할 수 있다.
- 먼저 시리얼 번호와, 그 문자열의 길이, 숫자의 합을 한번에 담아둘 클래스(구조체)를 작성하고 생성자를 만들어 ```v.push_back(serial(num));``` 이렇게 serial(num)을 해주면 필요한 값들을 잘 할당해 준다.
- 이후 compare함수를 통해 가장 먼저 길이순으로 정렬하고, 길이가 같으면 정수의 합을 비교한다.
- 정수의 합이 작은순으로 정렬하고, 정수의 합이 같으면 문자열을 사전순으로 정렬하기 위해 비교한다.
- c++의 string은 c의 strcmp함수가 없어도 <,>,=를 통해 대소비교가 가능하다.
=> [2021.02.10] jerimo 시리얼 번호 풀이

2.구현/시리얼 번호_shelly.py
- 우선 문제를 딱 보기에 함수화 하면 좋겠다 싶어서 함수를 잘게 나눠보았습니다.
- 함수는 하나의 기능만을 수행할 수 있도록 간결하게 짜는 것이 목적이었습니다.
- 함수를 기능별로 나눔으로써 가독성을 높이는 것을 기대했어요.
- 하지만 더 짧고 간단하게 짜는 분들도 계시겠죠.. 그 분들의 코드를 기대하고 있습니다. ✨
=> Create 시리얼 번호_shelly.py

4.정렬/단어정렬_jerimo.cpp
01.22일자 문제를 풀어보았다.
- 이전과 동일하게 algorithm의 sort함수, 조건에 맞게 코드를 짠 compare함수를 사용했다. (이젠 퀵정렬, 합병정렬 기억이 안나서 못 쓸 수준인거 같다... 그치만 이거 너무 신세계다..)
- 중복 검사를 할때 반복문으로 모든 원소를 다 찾도록 하다가 시간초과가 났었다.
- 새롭게 set(해쉬 set과 비슷..?) 컨테이너를 사용했다. set는 기본적으로 중복을 허용하지 않기 때문에 set에 넣고 새롭게 넣고자 하는 문자열을 set에서 찾은 뒤 존재하지 않을 때만 벡터에 삽입한다.
- set.find는 원소를 찾으면 해당 원소를 가르키는 이터레이터(포인터)를 반환하고 찾지 못하면 set.end()를 반환한다.
=> [2021.02.11] jerimo 단어 정렬 문제풀이

4.정렬/안테나_jerimo.cpp
- 이전에 풀었던 정렬 문제와 마찬가지로 집의 위치와 각각의 안테나로부터의 거리의 합을 저장할 클래스를 선언했고
- 이후에 이중포문을 통해 각 거리를 계산 후 sorting 하는 방법으로 처음 시도.
- 그러나 시간초과...
- 한참 생각하다가 그냥 가운데에 존재하는 집 출력.
- 바로 정답.. 약간 허무했다.. 차라리 시간 제한을 풀고 거리를 각각 계산하고 풀수 있도록 하는게 좀 더 취지에 맞는거 아닐까..? 이게 실버3..?
=> [2021.02.15] jerimo 안테나 문제풀이

4.정렬/안테나_lys7442.py
입력받은 집들을 정렬하고, 중간값을 구하면 끝나는 단순한 문제입니다.
처음엔 조건을 빼먹고 문제를 잘못 이해해서 
0부터 입력받은 배열중 최대값을 범위로 잡고
이진탐색으로 풀었습니다.
안테나의 위치는 집에만 설치할 수 있다는 조건을 확인 한 후
다시 풀었습니다.
=> [2021.02.15] lys7442 안테나 풀이

4.정렬/안테나_ghoon99.py
처음에 집을 정렬 후 집마다 방문하며 거리를 구한후 최소를 출력하면 되는 문제일줄 알았는데 
시간제한 1초와 20만의 숫자를 보니...하면 안될거 같았습니다
그래서 생각한 것이 모든 집의 위치 **평균에서 제일 가까운 집** 에 설치를 하면 되겠다라고 했는데 틀렸네요..
다르게 생각해보니**중앙에 설치** 하면 제일 작은거 같아서 해봤더니 통과..
뭔가 숫자는 훼이크 같아요 약간 허무한 문제였네요 ㅜㅜ
=> [2021.02.15]ghoon99 안테나 풀이

4.정렬/[2021.02.15] dydwo706 안테나
처음에 sort함수를 사용하지 않고
평균 위치에서 각 집의 위치까지 거리 차를 이용해서 풀려 했지만 틀렸고 반례를 못찾아서 
방법을 바꿨습니다
=> [2021.02.15] dydwo706 안테나

4.정렬/안테나_gusdn3477.py
거리의 합이 최소가 되기 위해선 중간 지점의 집에 안테나를 설치하면 됩니다.
값이 여러 개인 경우 최소를 출력하라고 했으므로,
값을 입력받은 뒤 오름차순으로 정렬 후 (길이 / 2 - 1)의 인덱스의 값을 출력하면 됩니다.
=> [2021.02.15]gusdn3477 안테나.py 풀이

5.이진탐색/공유기설치_lys7442.py
**이진탐색**은 반드시 **정렬된 배열**에서만 가능합니다.
따라서 탐색을 위해 입력받은 배열을 정렬하는 과정이 필수적입니다.
이진 탐색으로 풀 수 있는 이유는 
각 공유기 사이의 거리 값을 가능한 범위 내에서 탐색하는 문제이기 때문입니다.
```
if(해당값이 조건 만족) -> 구간 재설정 (거리값을 늘려서 조건을 만족하는 더 큰값을 찾자)
else ->구간 재설정 (거리값을 줄여서 조건을 만족하도록 변경)
```
(문제의 답이 x이라 할때, 거리를 1부터 반복문을 돌려
1,2,3,4, ... ,x, x+1(불가능) -> break return x 로 풀 수도 있겠으나, 아마 시간초과되지 않을까 싶습니다.)
그렇다면 조건을 만족하는지 판별하기만 하면 됩니다. 문제에 제시된 힌트를 읽어보면,
`"공유기를 1, 4, 8 또는 1, 4, 9에 설치하면 가장 인접한 두 공유기 사이의 거리는 3이고, 이 거리보다 크게 공유기를 3개 설치할 수 없다."` 라고 나와있습니다.
이 말은 사실 공유기의 위치에는 관심없다는 뜻입니다. 조건을 충족하는 조합은 수십가지가 나올 수도 있지만,
우리는 그 조합 중에 단 한가지 case만 발견할 수 있다면, 문제를 해결할 수 있습니다.
그래서 저는 `첫 원소를 반드시 포함하면서, 최소 거리 x를 보장하는 한가지 케이스`를 찾았습니다.
정렬된 배열을 순회하면서, 만약 ar[1]이 `ar[1] >= ar[0]+x` 를 만족한다면, ar[1]을 저장하고 카운트 합니다.
ar[2]가 ` ar[2]>=ar[1]+ x` (ar[1]은 아까 저장된 값)을 만족한다면 ar[2]를 저장하고 …
=> [2021.02.16] lys7442 공유기설치 풀이

5.이진탐색/예산_ghoon99.py
어제도 그렇고 이진탐색 문제는 안익숙하니까 어렵네요..
무엇을 기준으로 잡고 탐색을 해야되는지 잡으면 금방 풀릴듯도 했는데
무엇을 리턴해야 (start,end, mid ??)될 지도 생각이 꼬이고 
start 를 arr[0] 으로 초기화 하니 자꾸 틀렸다 떠서 
그냥 0 으로 바꾸고 하니까 통과하네요...
연습이 많이 필요한 유형인거 같습니다 ㅜㅠㅠ
=> [2021.02.17]ghoon99 예산 풀이

6.다이나믹 프로그래밍/2xn 타일링 2_ghoon99.py
3개까지 세면서 규칙을 계속 찾아보다가 
다이나믹프로그래밍...을 생각해보다가 이전꺼에 + 무엇 을 해야 되는지로 사고 방식을 바꿨습니다
그러니 n-1번째의 개수 + 타일 1개 , n-2번째의 개수+타일 2x2 짜리 1개, 1x2짜리 1개 해서 2개 
2x1 짜리 2개는 n-1 에 포함이라 불가능 
따라서 
dp[n] = dp[n-1] + 2 * dp[n-2] 라는 식이 나왔습니다
주어진 n 까지의 수를 다 구해서 dp[n]을 출력하였습니다
=> [2021.02.18]ghoon99 2xn 타일링 2 풀이

6.다이나믹 프로그래밍/RGB거리_ghoon99.py
이갈고 풀었습니다.... 진짜...
```py
result = min(arr[0])
prev =arr[0].index(result)
for house in range(1,n):
min_value = returnMin(prev,arr[house])
prev = arr[house].index(min_value)
result+=min_value
#print(min_value,prev)
print(result)
```
전부 돌면서 색칠이 가능한곳의 최소값을 계속 더해줌
하지만  그 순간순간에 최소값을 고르면 전체적으로 최소값이 되는것을 보장하지 못함
=> 그리디알고리즘 X 
처음집이 R,G,B 로 시작하고 그 다음 부터 그 순간의 최소를 구하게
결과는 [R부터 시작, G 부터 시작,B부터 시작]  중 최소값 을 출력 
=> 첫번째 방법에서 시작 방법만 3가지로 나눴지 순간의 최소를 구하는 오류를 그대로 씀
거꾸로 생각.. 만약 마지막 집이 R 로 칠했으면 그전은??
=> B또는 G
값이 최소가 되게 하려면?
=> B또는 G 중 최소값 
최소가 G였으면 
.....  G, B 순이였고 마지막집을 G 라고 생각하면 처음까지 계속 반복..  
- 다시 한번 설명
현재 R 이면 이전에 G 또는 B 를 골랐을거고 그 중에 최소를 골라서 지금으로 온것이라고 생각
또 이전에 G 를 골랐다면 이전의이전은 R 또는 B 를 골랐고 그중 최소를 골라서 그 이전으로 왔다고 생각....
이게 뒤로 계속 반복된다...
이것을 수식으로 나타낼수가 있게 되었는데
-현재 R 일때 `(R)dp[n] = 현재R값 + min((G)dp[n-1], …
=> [2021.02.19]ghoon99 RGB거리 풀이

7.최단경로/최단거리:최소비용구하기_ceroopark.py
오답이다. 플로이드 와샬을 이용하여 문제를 해결하려고 했는데, 오류가 났다.
+ 혹시 코드 좀 봐주실 분 계신가요? 플로이드 와샬로 접근하려 했는데, 잘 안되네요 ..
=> [2020.02.20] ceroopark 최소비용구하기

7.최단경로/최소비용 구하기_ghoon99.py
학교서 배웠던 다익스트라 알고리즘이 생각나서 그대로 구현해보고 시간제한을 봤더니 좀 적더라구요..
그래서 더 개선된 다익스트라 알고리즘을 우선순위 큐를 이용하여 직접 구현하였습니다..
식 같은건 막 외우기 어렵진 않은거같은데 코드로 또 구현하니까 쉽지는 않네요
아예 모르면 구현조차 안되는거니 한번 외워두면 잘 쓰일거같습니다
=> [2021.02.20]ghoon99 최소비용 구하기 풀이

7.최단경로/플로이드_ghoon99.py
정직한 플로이드와샬 알고리즘 구현..
조건에 **시작 도시와 도착 도시를 연결하는 노선은 하나가 아닐 수 있다** 때문에 몇번 틀림..
입력 받을때 처리를 잘해줘야되네요
=> [2021.02.21]ghoon99 플로이드 풀이

7.최단경로/최단경로:플로이드_ceroopark.py
어제 문제를 플로이드를 활용하면 안되는 문제여서 실패 하였지만, 이 문제는 플로이들 활용한 문제이다.
처음 문제를 틀렸는데, 양방향이 아님을 인지하지 못하여(편방향) 이 부분에서 오류가 있었던 것으로 확인되었다.(어제도 마찬가지)
플로이드로 문제를 정상적으로 푼 것처럼 보였지만, 백준 컴파일러에 집어넣은 결과 시간초과가 떠 버렸다.
그래서 구글에서 돌아다니는 소스코드들을 참고해보았다.
보완점
1) 2차원 배열로 설정을 함 에 있어서, 시작점을 0~N-1 이 아닌 1~N으로 해서 좀 더 직관적으로 하게 고안해야 할 듯 하다.
2)i==j 일 때, 갱신하지 않기
처음 짠 코드
N=int(input())
M=int(input())
INF=100000000
a=[[INF]*N for i in range(N)]
for i in range(M):
start, end, price=map(int, input().split())
if a[start-1][end-1]>price:
a[start-1][end-1]=price
for k in range(N):
for i in range(N):
for j in range(N):
if i!=j and a[i][j] > a[i][k]+a[k][j]:
a[i][j]=a[i][k]+a[k][j]
for i in range(N):
for j in range(N):
if i==j:
print("0 ", end="")
#a[i][j]=0
else:
print("%d "%(a[i][j]), end="")
print("")
이 코드의 정확한 문제를 아직 진단하지 못해서 연구해 볼 필요가 있다..
=> [2020.02.21] ceroopark 플로이드

1.그리디알고리즘/2+1세일_gusdn3477.py
생각보다 간단히 풀렸습니다. 
문제의 조건 1) 꾸러미가 완성된 경우 가장 싼 것이 공짜 2) 꾸러미가 아닌 경우 개별 가격 다 내야 함
을 고려해 보았을 때,
꾸러미 안의 가장 싼 것이 전체적으로 봤을 때 비싼 편에 속하여야 한다고 생각하였고 예시2 에서 꾸러미 안의 3개의 가격이 모두 같은 경우에도 2+1이 적용하는 것을 보고 내림차순 정렬이 가장 효과적이라 생각하였습니다.
내림차순 정렬 후 ct라는 변수를 두고 3의 배수가 될 때마다 0으로 리셋시키고 continue로 total에 값이 더해지지 않게 하였습니다.
값을 출력하니 정답이더군요.
PS 1)
2월 21일까지 제출해야 하는 자소서와 포트폴리오 덕분에(?) 이 곳에 기여하지 못하게 되었습니다. 허허.. 다시 열심히 달려보겠습니다.
PS 2)
input과 sys.stdin.readline() 성능 차이입니다. 꽤 크군요.
=> [2021.02.22]gusdn3477 2+1세일 풀이

1.그리디알고리즘/2+1 세일_ghoon99.py
오랜만의 그리디 알고리즘이네요 
입력 예시가 그렇게 막 좋지는 않아보입니다 ㅠㅠ 
몇개 만들어서 해봤더니 답이 보였네요
그냥 내림차순으로 정렬한뒤 3개씩 묶고 
나머지는 그냥 하나씩 구입하면 최소비용이네요
젤 비싼거부터 내려오며 할인 먹이니 최소인거같습니다
=> [2021.02.22]ghoon99 2+1 세일 풀이

1.그리디알고리즘/신입사원_ghoon99.py
처음에 서류등수 를 기준으로 오름차순 정렬한뒤에 
내가 뒤에있는사람들보다 면접등수가 높으면 되겠지 하고 
이중 반복문을 돌았습니다. 역시 시간초과가 나더라구요...
그래서 생각을 바꿔 바로 뒤에있는사람하고만 비교를 하면 
반복문 1번에 돌수있지 않을까 하다가 반례를 발견하고
바로 뒤에있는사람이 아니라 최종선발된 사람의 면접등수를 저장하여
그것과 비교하는 식으로 바꾸었습니다 
그리고 통과!! 하는 듯 싶었는데...
분명 nlogn에 반복문 1번만 도는데 시간초과가 나길래
sys.stdin.readline으로 바꿧더니 통과되네요 
인풋을 for 문 안에서 받을때는 그냥 input 받으면 안되네요 ㅠㅠ
=> [2021.02.23]ghoon99 신입사원 풀이

1.그리디알고리즘/신입사원_gusdn3477.py
3번의 시간 초과 후에 좌절하고 일어난 뒤, 약간의 아이디어 참고로 통과하였습니다.
시간 초과 이유는, sort 함수를 통하여 정렬하였음에도 불구하고 2중 for문을 통하여 검사를 하고 있었습니다.
또한 같은 등수가 존재하지 않기에 정렬을 하게 되면 하나의 요소만 검사하면 되는데, 거기서 또 2가지 요소를 다 검사하였습니다.
일단 이렇게 된 근본적 원인은 문제에 대한 감을 못 잡은 게 큽니다.
사실 아이디어 참고를 안 해도 어찌 어찌 하여 풀었을 것 같긴 한데, 이게 왜 그리디 알고리즘인지 감이 잡히지 않아
어느 부분이 그리디 알고리즘인지에 대한 궁금증 해결을 위해 그 부분에 대하여 알아보았구요.
핵심 아이디어는 일단 정렬 후에기준점을 첫 번째 인덱스의 두번째 요소로 둔 뒤에, 
반복문을 통해  각 인덱스의 두 번째 요소만 비교하여 현재 기준보다 크면 무시하고, 그렇지 않으면
기준점을 현재 돌고 있는 인덱스의 두 번째 요소로 만들고 다른 것들과 비교하는 것 같습니다.
문제 유형이 나와있지 않았다면 더 헤맬 뻔 하였습니다.
=> [2021.02.23] gusdn3477 신입 사원 풀이

2.구현/개미_gusdn3477.py
처음에 좀 막막하다가 5초 뒤에 평안을 되찾은 문제입니다.
총 3가지 케이스로 나뉘는데
1) 각자 자신에게 가까운 방향으로 가는 경우(즉 서로 만날 일 없음)
2) 서로 만나서 뒤엉키는 경우
3) 모두가 한 방향으로 가는 경우(서로 만날 일 없음)
2번은 구현이 복잡하다고 생각했는데 조금만 생각해 보니 2번의 경우보다 3번의 경우가 더 최악이라는 것을 알게 되었습니다.
왜냐면 2번의 경우 최악을 떠올리게 되면, 시작점과 끝 점이 서로 다가오다 부딪힌 뒤 반대 방향으로 가는 것 혹은 중간에 있는 것이 핑퐁을 하다 시간을 버리고 한 방향으로 가는 경우를 떠올렸는데 둘 다 시작점에서 끝 점으로 가는 것보다 1정도 작게 나오더라구요(정확하진 않습니다.)
사실 문제 설명이 조금 아쉬운데, '두 개미가 만나게 된다면' 에서 설명이 너무 대충 나와있어서 이 상황이 답이 아닐 것이라 확신(?)을 가지고 풀었습니다.
두 개미가 만나게 된다면 이라는 것은 같은 지점에서 만난다는 건데, 3과 4에서 각자 4, 3으로 이동하는 지점 즉 3.5에서 만날텐데 이런 경우만 생각해도 복잡해 지는데 설명이 좀 부실합니다.
그래서 1, 3의 케이스로 풀었고
1의 경우 중간 지점에서 가장 가까운 개미의 위치를 찾았고, 그것의 시작 점과 끝 점에서 거리 중 작은 값을 답으로 하였고
3의 경우 정렬 후에 0번 인덱스와 마지막 인덱스를 고른 뒤, 0번 인덱스에서의 끝점의 거리와 마지막 인덱스에서 시작점 거리 중 큰 값을 답으로 하였습니다.
=> [2021.02.24] gusdn3477 개미 풀이

6.다이나믹 프로그래밍/RGB거리_jerimo.cpp, 7.최단경로/최소비용구하기_jerimo.cpp
- dp문제를 거의 처음 풀어보게 되어서 처음  문제 이해도 어려웠고 알고리즘도 기억이 잘 안나서 책을 찾아보고 예제 문제들을 풀어보고 나서야 이해가 좀 됐다.
- 생각을 잘못해서인지 도저히 혼자서는 코드의 기본 틀조차 짜기 어려웠다.. 다이나믹 프로그래밍은 스스로 좀 더 문제를 풀어봐야 할 것 같다. 
- dp테이블을 따로 두어서  각 색을 칠할 때, i-1번째 집과는 색이 달라야 하므로 남은 두가지 색 중 작은 값을 취해서 더한다.
=> [2021.02.19] jerimo RGB거리 문제풀이

2.구현/개미_ghoon99.py
어...뭔가 찝찝한 문제..
그냥 최소는 다리를 절반 가른뒤 왼쪽에 있으면 다 왼쪽으로 보내고 오른쪽에 있음 다 오른쪽에 보내면 나오더라구요
최대는 이리저리 치고 박고 해서 길게 나올거 같았는데 또 만난다의 기준이 애매해서...
마주본 상태서 2 4 에 있으면 1초뒤 3 3 이 되서 만나서 반대로 가는건지
2 5에 있으면 1초뒤 3 4가 되서 만나서 반대로가는건지 애매하네요..
그래서 일단 안만나게 제일 멀리 떨어진 개미가 제일 나중에 떨어지게 한방향으로 다 떨궜더니 예시가 맞길래
제출했더니 통과.... 
흠...?
=> [2021.02.24]ghoon99 개미 풀이

2.구현/뱀_lys7442.py
처음엔 N*N 배열을 만들어서 뱀이 들어있으면 1 아니면 0 사과는 2 이런 식으로 풀려 했으나
시간초과될거 같다는 생각이 들어서 Deque로 풀었습니다.
제출하는데 자꾸 틀려서 문제를 다시 읽어보니까 
`먼저 뱀은 몸길이를 늘려 머리를 다음칸에 위치시킨다.`
라고 되어있었습니다. 
이 말은 꼬리 위치로 뱀이 이동할 때, 꼬리를 쏙 빼고 머리가 들어갈 수 없다는 뜻이라서
이 부분을 수정했더니 맞았습니다.
이후 다른 풀이를 찾아보니  제 풀이보다 훨씬 깔끔한 풀이가 많은 것 같습니다.
1. 그냥 큐로만 풀었는데 N*N 매트릭스를 같이 활용하면 더 효율적으로 풀 수 있습니다.
2. 동서남북 이동도 dx=[0,0,-1,+1] dy=[1,-1,0,0] 이런식으로 한다면 깔끔하게 숏코딩이 가능해집니다.
```python
from sys import stdin
from collections import deque
n=int(stdin.readline()) #보드의 크기
k=int(stdin.readline()) #사과의 개수
apple=[list(stdin.readline().rstrip().split()) for _ in range(k)]
l=int(stdin.readline()) #방향 변환 횟수
change=[list(stdin.readline().rstrip().split()) for _ in range(l)]
boundary=[0,n+1]
directions=['r','d','l','u'] 
now_dir=0
time=0
que=deque([(1,1)]) #1,1에서 시작
while(1):
time+=1 …
```
=> [2021.02.25] lys7442 뱀 풀이

2.구현/뱀_gusdn3477.py
문제에서 요구한 대로 구현하기만 하면 정말 딱 맞게 풀리는 문제였습니다.
핵심 아이디어를 적어보면, 뱀의 위치를 기억해 두는 것이 중요한 것 같습니다.
뱀이 이동한다고 쳐도, 결국 새로 생기거나 없어질 부분은 자료 구조의 처음과 끝이기에 처음와 끝 부분만 처리하는 것이 필요하다고 생각했습니다.
저는 deque를 이용하여 사과가 있으면 뱀의 위치를 새로 추가하고, 사과가 없으면 popleft로 0번 인덱스의 요소를 제거했습니다.
또한 새로 간 위치가 인덱스 밖이거나 현재 뱀 위치의 요소와 겹치면 끝나도록 설계했습니다.
마지막으로 회전의 경우 nx, ny로 이동 방향을 정리해 둔 뒤, (+1 혹은 -1) % 4 로 설정해두었습니다.
퀄리티가 좋다고 생각했는데 역시 삼성 역량테스트 기출 문제네요. 
소요된 시간은 152ms 입니다.
=> [2021.02.25] gusdn3477 뱀 풀이

1.그리디알고리즘/그리디알고리즘:2+1세일_ceroopark.py
늦게 제출하게 되었습니다.
기본 알고리즘은 최소 비용을 구하기 위해 
높은 순으로 정렬 한 후 모듈 연산자를 통한 합 입니다.
=> [2021.02.22] ceroopark 2+1 세일 풀이

2.구현/뱀_jerimo.cpp
아주 차근차근 문제를 따라서 구현해나가니까 코드가 완성됐다.
- 일단 방향을 dist배열에 저장해놓고 distN을 통해 명렁어에 따라 방향을 설정해 준다. 모듈러 연산 대신 명령어 배열 길이를 넘어가면 각각 4를 더하고 빼줬다. 
- deque 대신에 비슷한 역할을 할 수 있는 list를 사용해 뱀의 위치를 기록한다.
한참을 숫자가 1씩 차이나서 뭐가 문젤까 했더니
x, y, sec을 변경하는? 위치를 가장 위로 옮겼더니 답이 잘 나왔다. 
역시 구현은 문제를 *그대로* 따라가야한다.
방향은 초가 지난 후에 바꾸는 거니까 방향변경을 젤 나중에 해야한다.
첨 코드짠게 새벽이어서 하도 비몽사몽했는지 경계선 검사하는 부분에 y>0||y<=n이라고 해놨었다.. (근데 또 x는 제대로 썼다...) 무튼 그것땜에 한참 디버깅했다..
=> [2021.02.25] jerimo 뱀 문제풀이

3.그래프 이론_탐색/유기농배추_lys7442.py
```python
from sys import stdin
from collections import deque
t=int(stdin.readline()) # Test Case
for test in range(t):
m,n,k=map(int,stdin.readline().split()) #가로길이,세로길이,배추개수
arr=[[0 for row in range(m+2)] for col in range(n+2)] #밭
for _ in range(k):
x,y=map(int,stdin.readline().split()) #각 배추 위치  
arr[y+1][x+1]=1
cnt=0 #필요한 지렁이 수
for i in range(1,n+1):
for j in range(1,m+1):
#배추 발견
if(arr[i][j]==1):
que=deque([(j,i)])
arr[i][j]=2 #is visited
while(que):
x,y=que.popleft()
if(arr[y-1][x]==1):
que.append((x,y-1))
arr[y-1][x]=2
if(arr[y+1][x]==1):
que.append((x,y+1))
arr[y+1][x]=2
if(arr[y][x-1]==1):
que.append((x-1,y))
arr[y][x-1]=2
if(arr[y][x+1]==1):
que.append((x+1,y))
arr[y][x+1]=2
cnt+=1
#for k in range(n+2):
#print(arr[k])
print(cnt)
```
핵심 아이디어 자체는 간단합니다. 
다만 x,y +-1씩의 이동을 구현할 때 …
=> [2021.02.26] lys7442 유기농배추 풀이

3.그래프 이론_탐색/유기농 배추_gusdn3477.py
1이 뭉쳐있는 지점이 총 몇 개인지를 찾는 문제였습니다.
비슷한 문제를 여기서 풀었던 기억이 납니다.
핵심 아이디어는 메인 함수에서 2중 반복문으로 조건에 해당하는 곳에 DFS 혹은 BFS 함수를 실행하는 것 같습니다.
visited 라는 새로운 배열 대신 값이 1인 경우 0으로 바꿔주는 방식을 이용하였습니다.
커밋할 때 유기농 배추를 양배추라고 썼네요..ㅋㅋ
=> [2021.02.26] gusdn3477 유기농 배추 풀이

3.그래프 이론_탐색/그래프이론:유기농배추_ceroopark.py
처음에 RUNTIME 오류가 발생하였다.
C 같은 언어와 달리 파이썬은 재귀에 있어서 제한이 걸려있기 때문에,
그를 늘려줘야 한다는 글을 보고
setrecursionlimit  을 걸어주었다.
=> [2021.02.26]ceroopark 유기농배추 풀이

3.그래프 이론_탐색/유기농 배추_jerimo.cpp
- dfs를 이용해 간단하게 해결방법을 찾았다. 
- 테스트 케이스별로 find함수에서는 2중 for문을 돌며 배추가 있는지 찾는다
- 배추를 찾으면 dfs를 재귀적으로 호출하여 한 덩어리를 찾아낸다.
- 방문 여부는 visit 함수에 따로 저장한다.
- 이때 배추 무리를 적절하게 찾았다면 (cnt != 0) 흰지렁이의 수를 하나 늘린다. (rst++)
- 이후 find함수를 출력한 뒤 map과 visit 함수를 초기화해준다.
=> [2021.02.26] jerimo 유기농 배추 문제풀이

3.그래프 이론_탐색/미로 탐색_gusdn3477.py, 4.정렬/보물_gusdn3477.py
문제 내용 중, 최소의 칸을 보고 BFS로 풀게 되었습니다.
BFS로 순회하며 현재 인덱스의 값을 '0'으로 초기화 해 주고, 상하좌우를 돌며 덱에 넣은 뒤
꺼내어 그것의 상하좌우를 체크하는 것을 반복하였습니다.
visited라는 배열을 만들어 순회마다 방문 전의 인덱스 + 1  값으로 만들었습니다. (거리를 담는 리스트입니다.)
현재 인덱스가 N-1, M-1이 되면 종료하게 하였습니다.
추가로 공부할 점은
문자열을 리스트에 넣는 것과, 문자열 리스트를 리스트에 넣는 것에 대해 공부가 좀 필요해 보입니다.
PS. 방장님 ~ 무리하지 마시고 푹 쉬는 것도 좋아 보입니다.
=> [2021.02.27] gusdn3477 미로 탐색 풀이

3.그래프 이론_탐색/그래프이론:미로탐색_ceroopark.py, 4.정렬/정렬:보물_ceroopark.py
1) BFS 문제이니, dx, dy  설정해서 동서남북 방향으로 탐색을 한다.
2) 탐색을 할 때 있어 단순히 가지 말고, 각각의 방향으로 진출 했을 때의 소요 거리를 갱신해준다.
3) 큐를 사용하여 구현하며, 거친 좌표는 지워준다.
=>  [2021.02.27]ceroopark 미로찾기 풀이

1.그리디알고리즘/잃어버린 괄호_ jerimo.cpp
- 가장먼저 스트링을 돌면서 숫자와 연산자를 각각의 리스트에 넣는다
- 숫자의 경우는 스트링에 숫자만 뽑아낸 다음, 1의자리 숫자부터 계산해서 넣었다.
- 그 다음에는 연산자가 들어있는 리스트가 비기 전까지 반복문을 돌며 계산하는데,
- 연산자가 -이면 ```flag를 true로 바꿔주고``` 값들을 모두 빼준다.
=> [2021.03.02] jerimo 잃어버린 괄호 문제풀이

1.그리디알고리즘/1541_잃어버린 괄호.py
이렇게 풀어도 되나.. 라는 생각이 들었습니다.
결국 최솟값이 나오기 위해선 + 연산자 좌우 숫자에 괄호를 치는 과정이 필요한데요.
그냥 숫자, 연산자 담는 deque 만들고, 각자 담은 뒤에
while문에서 + 연산자가 deque에 존재할 때 까지 + 의 인덱스를 알아낸 뒤, 제거하고
인덱스 좌우 숫자 del로 제거해주고 더해서 다시 append해줬습니다.
이렇게 되면 결국 두 개의 리스트엔 덧셈이 된 숫자와 - 연산자만 존재합니다.
뺄셈 연산을 한 뒤 출력하였습니다.
그리디 알고리즘으로 풀어야 하는데 숫자 또한 문자열로 나오기 때문에 변환하는 과정에서
더 필요한 것은 문자열 처리, 자료 구조 등 인것 같습니다.
=> [2021.03.04] gusdn3477 잃어버린 괄호 풀이

1.그리디알고리즘/그리디알고리즘:잃어버린괄호_ceroopark.py
늦게나마 올립니다.
더하기 빼기 로 구성된 식에서
최소값을 구하기 위해선 빼는 값이 최대가 되어야한다는 것을 고려하여 푼 알고리즘입니다.
=>  [2021.03.06] ceroopark 잃어버린괄호 풀이

2.구현/컨베이어벨트위의로봇_20055.py
저만 문제가 이해가 잘 안 되었나요?
내려간다는 의미가 컨베이어 벨트 밖으로 나간다는 것을 이해하지 못하여 시간을 많이 보냈네요.
구현 내용은 어렵지 않으나 문제가 너무 이해가 되지 않아 힘든 문제였습니다 ㅠㅠ
이것도 삼성 역량테스트 기출 문제라고 하는데, 전에 풀었던 문제랑 정말 패턴이 유사합니다.
말 그대로 구현만 하면 되네요. 근데 그게 어렵습니다.. 실력을 더 키워야 겠습니다.
+ 문제가 이해가 되지 않아 문제 이해에 다른 풀이를 조금 참고하였고, 그 분들도 문제를 헷갈리셨다고 하네요
+ 이 문제가 삼성 역량테스트 중에서 쉬운 축이었다고 합니다. 더 열심히 해야겠습니다.
=> [2021.03.07] gusdn3477 컨베이어 벨트 위의 로봇 풀이

2.구현/컨베이어벨트 위의 로봇_lys7442.py
단순 구현 문제로,  배열을 모듈러 연산(%)을 이용해 처음과 끝이 이어진 원형 배열로 생각하고 풀면 풀리는 문제입니다.
내려가는 위치에 로봇이 있는 경우 **즉시** 땅으로 내려가야 한다. 라는 조건만 유의하면 쉽게 해결할 수 있을 것 같네요.
=> [2021.03.07] lys7442 컨베이어 벨트 위의 로봇 풀이

4.정렬/좌표 압축_gusdn3477.py
이분 탐색을 이용하여 풀었습니다.
리스트 하나를 복사한 뒤, 그것을 set, list, sort를 하여 중복되는 요소를 줄이고 정렬하였습니다.
bisect_left라는 함수는 어떠한 값이 리스트의 어느 위치에 들어가는지 반환하는 함수인데, bisect_right와 다른 점은
자신과 같은 값을 만난 경우 bisect_left는 그 값의 인덱스를, bisect_right는 그 값의 오른쪽 인덱스를 반환하는 것이 차이입니다.
즉, bisect_left 함수를 사용하여 초기 리스트의 값으로 for문을 돌며 bisect_left 함수를 통해 변환된 리스트에 적용한 값을 출력하면 정답이 나옵니다.
시간은 1728ms 소요되었습니다.
=> [2021.03.12] gusdn3477 좌표 압축 풀이

4.정렬/정렬:좌표압축_ceroopark.py
=> [2020.03.16] ceroopark 좌표압축 문제풀이

용액_gusdn3477.py
이분 탐색으로 풀려고 했으나.. 감이 잡히지 않아 투 포인터라는 알고리즘으로 풀었습니다.
상세 내용은 링크 첨부하겠습니다.
https://m.blog.naver.com/kks227/220795165570
투 포인터의 경우 O(N) + O(N) = O(N)이 성립합니다.
일단 용액의 수는 최대 100000개 이므로 충분히 가능합니다.
a,b를 각각 첫 인덱스의 값과 마지막 인덱스의 값으로 설정한 뒤, 두개의 합의 절댓값과 우리가 설정한 초깃값을 비교하여 범위를 조정하시면 됩니다.
조심해야 할 점은, 입력받는 값의 범위가 -10억~10억이므로, 10억, 10억+1 의 경우가 될 수 있으므로
초깃값을 20억 + 1 초과값으로 설정해야 합니다. (저는 20억+1로 풀었는데 통과되네요. 테스트 케이스 부족으로 인한 오류같습니다.)
=> [2021.03.18] gusdn3477 용액 풀이

6.다이나믹 프로그래밍/이동하기_lys7442.py
처음엔 재귀로 풀었다가 
깊이가 너무 깊어져서 런타임 에러가 나서 
깊이를 재설정 하니
메모리 초과가 발생했습니다.
그래서 DP 메모이제이션으로 풀었습니다.
문제 풀기 전 시간 공간 복잡도를 보고 어떤 풀이를 택할 지
미리 예상해야겠다는 생각이 들었습니다.
=> [2021.03.19] lys7442 이동하기 풀이

7.최단경로/알고스팟_gusdn3477.py
평범한 DFS, BFS 문제와 다른 문제였습니다. 
BFS로 풀게 되면 최단거리는 찾을 수 있으나, 벽을 최소로 부수는 거리는 찾지 못하게 됩니다.
왜냐하면 queue에 들어가는 좌표의 순서대로 순회하기 때문입니다.
벽을 최소로 부수며 가는 최단거리를 찾기 위하여 해당 좌표값이 1인 경우엔 append로 큐의 맨 뒤에 넣고,
0인 경우엔 appendleft로 1인 지점들보다 먼저 꺼내게 하였습니다. 그렇게 되면 0인 지점들 기준으로 먼저 순회하게 됩니다.
이 외에도 heapq를 이용한 풀이 등도 있으나 원리는 비슷하다고 생각됩니다.
최단 거리 알고리즘에 대해서 공부를 더 해봐야 겠습니다.
```
from collections import deque
def BFS(x, y, ct):
queue = deque()
queue.append([x, y, ct])
while queue:
a = queue.popleft()
if a[0] == N - 1 and a[1] == M - 1:
print(a[2])
return
for i in range(4):
dx = a[0] + nx[i]
dy = a[1] + ny[i]
if dx < 0 or dx >= N or dy < 0 or dy >= M:
continue
if visited[dx][dy] == 0:
visited[dx][dy] = 1
if arr[dx][dy] == '1':
queue.append([dx, dy, a[2] + 1])
else:
queue.appendleft([dx, dy, a[2]])
M, N = map(int, input().split())
arr …
```
=> [2021.03.23] gusdn3477 알고스팟 풀이

1.그리디알고리즘/통나무 건너뛰기_gusdn3477.py
처음와 끝을 포함한 각 요소들의 차를 최소로 하되, 그 최소중 최댓값을 출력하는 문제였습니다.
사실상 처음과 끝은 무의미하기에, 원형으로 되어 있는 자료구조라고 생각하면 편하겠네요.
원형으로 되어있는 구조기에 어디서 보든 간에 차가 최소가 되어야 하므로, 결국 리스트 기준으로 가운데 요소까지 오름차순으로 되어 있으며, 가운데 이후부터 내림차순으로 되어야 하는 것을 알 수 있습니다.
위의 조건을 만족하기 위해서 가운데에 위치한 요소가 최대가 되어야 하므로 결국 리스트를 오름차순 뒤에 한 요소씩 띄어가며 append하고, append되지 않은 요소들을 내림차순 방향으로 append한 뒤 그 요소들의 차를 0으로 초기화 한 뒤, max 함수를 이용하여 업데이트 하면 됩니다.
리스트 요소의 갯수가 홀수 즉, [1,3,2,4,5] 의 경우 -> [1,2,3,4,5]로 정렬한 뒤, 새로운 리스트에 [1,3,5]를 append하고 [4,2]를 차례대로 append하면 됩니다.
짝수인 경우는 홀수의 경우와 다르게 [1,3,2,4,5,6] -> [1,2,3,4,5,6] 으로 정렬한 뒤, [1,3,5], [6,4,2] 식으로 append하면 됩니다.
최댓값이 나중에 append되긴 하지만 가운데 쪽에 위치하는 것은 변하지 않습니다. for문에서 범위만 조금 바뀌는 정도입니다.
```
from sys import stdin
T = int(input())
for i in range(T):
N = int(input())
poc = []
arr = list(map(int, stdin.readline().split())) …
```
=> [2021.03.24] gusdn3477 통나무 건너뛰기 풀이

2.구현/테트로미노_gusdn3477.py
정말 문제에 나온 그대로 구현했습니다. 종이와 펜 없이 풀어 상상력이 부족한 저에게 힘든 문제였습니다.
회전, 대칭을 합치면 약 19가지의 케이스가 나옵니다. 대칭은 구현 가능할 것 같은데 회전의 경우 어떻게 할 지 몰라서 그냥 노가다로 모든 경우의 수를 구했습니다. 각 리스트에 좌표들을 구했습니다.
2중 for문을 돌며 각 요소에 리스트의 좌표들을 더하여 범위 안에 있으면 True를, 그렇지 않다면 False를 반환합니다. (isTrue 함수를 이용하였습니다.)
True가 반환된 경우 Total 함수를 통하여 그 좌표에 해당하는 배열의 값을 더해 줍니다.
그리고 max를 통하여 업데이트 하면 됩니다.
매번 느끼지만 코딩에 대한 재능 여부는 구현 문제에 대한 코드로 나타나는 것 같습니다 ㅠ
=> [2021.03.28] gusdn3477 테트로미노 풀이
